"""Static assets for the public restaurant ordering panel."""

# ruff: noqa: E501

PUBLIC_RESTAURANT_ORDER_STYLE = """\
:root{--bg:#f7f4ee;--ink:#18212f;--muted:#687385;--line:#ded6ca;--surface:#fffdf8;--surface-2:#f0ece4;--accent:#0f766e;--danger:#b42318;--shadow:0 18px 50px rgba(24,33,47,.12);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink)}button,input,textarea,select{font:inherit}button{cursor:pointer}.order-shell{max-width:1040px;margin:0 auto;padding:22px 16px 56px}.order-top{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;margin-bottom:18px}.brand h1{margin:0;font-size:28px;line-height:1.1}.brand p{margin:6px 0 0;color:var(--muted)}.pill{display:inline-flex;border:1px solid var(--line);border-radius:999px;background:rgba(255,255,255,.72);padding:8px 12px;font-weight:800}.panel{border:1px solid var(--line);border-radius:18px;background:var(--surface);box-shadow:var(--shadow);padding:18px}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.grid-2{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.card{border:1px solid var(--line);border-radius:14px;background:#fff;padding:14px;text-align:left}.card strong{display:block;font-size:17px}.card small{display:block;margin-top:6px;color:var(--muted)}.card.active{border-color:var(--accent);box-shadow:0 0 0 3px rgba(15,118,110,.12)}.primary,.secondary,.danger{min-height:44px;border-radius:12px;border:1px solid transparent;padding:10px 14px;font-weight:900}.primary{background:var(--accent);color:#fff}.secondary{background:#fff;color:var(--ink);border-color:var(--line)}.danger{background:#fff1ef;color:var(--danger);border-color:#fac5bd}.toolbar{display:flex;gap:10px;flex-wrap:wrap;margin:14px 0}.toolbar a{text-decoration:none}.items{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:14px}.item-title{display:flex;justify-content:space-between;gap:10px}.item-title b{font-size:15px}.price{font-weight:900;color:var(--accent);white-space:nowrap}.muted{color:var(--muted)}.field{display:grid;gap:6px;margin:12px 0}.field label{font-weight:850}.field input,.field textarea{width:100%;border:1px solid var(--line);border-radius:12px;background:#fff;padding:12px}.summary{display:grid;gap:10px}.summary-row{display:flex;justify-content:space-between;gap:10px;border-bottom:1px solid var(--line);padding-bottom:8px}.footer-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:18px;flex-wrap:wrap}.empty{border:1px dashed var(--line);border-radius:14px;padding:16px;color:var(--muted);background:var(--surface-2)}.notice{border-left:4px solid var(--accent);background:#e9f7f4;border-radius:12px;padding:12px;margin:12px 0}.error{border-left-color:var(--danger);background:#fff1ef;color:#7a271a}.stepper{display:flex;gap:6px;margin:0 0 16px}.dot{height:8px;flex:1;border-radius:999px;background:#ded6ca}.dot.active{background:var(--accent)}[hidden]{display:none!important}@media(max-width:760px){.grid,.grid-2,.items{grid-template-columns:1fr}.order-top{display:block}.pill{margin-top:12px}.footer-actions{justify-content:stretch}.footer-actions button{width:100%}}\
"""


PUBLIC_RESTAURANT_ORDER_SCRIPT = """\
const app = document.getElementById('orderApp');
const token = new URLSearchParams(window.location.search).get('t') || '';
const state = {step:'loading',cfg:null,lang:'tr',meal:'',cart:{},serviceType:'table_service',roomNumber:'',customerNote:'',allergyNote:'',submitting:false,success:null,error:''};
const i18n = {
  tr:{title:'Kassandra Restaurant Sipariş',lead:'QR ile masa siparişi',language:'Dil seçin',meal:'Hangi öğün için sipariş vermek istiyorsunuz?',breakfast:'Kahvaltı',lunch:'Öğle',dinner:'Akşam',continue:'Devam',back:'Geri',menu:'Menü',pdf:'PDF menüyü aç',add:'Ekle',cart:'Sepet',empty:'Sepetiniz boş.',service:'Servis tipi',table:'Masa servisi',room:'Oda servisi',roomNo:'Oda numarası',note:'Sipariş notu',allergy:'Alerji / özel tercih',confirm1:'1. teyit: Sepetiniz doğru mu?',confirm2:'2. teyit: Siparişi restorana göndermek istiyor musunuz?',send:'Siparişi Gönder',pending:'Siparişiniz restorana iletildi, personel onayı bekleniyor.',staff:'Personel siparişi admin panelden kabul edecektir.',pricePending:'Fiyat personel onayında',total:'Toplam',tryAgain:'Tekrar deneyin'},
  en:{title:'Kassandra Restaurant Order',lead:'Table ordering by QR',language:'Choose language',meal:'Which meal period would you like?',breakfast:'Breakfast',lunch:'Lunch',dinner:'Dinner',continue:'Continue',back:'Back',menu:'Menu',pdf:'Open PDF menu',add:'Add',cart:'Cart',empty:'Your cart is empty.',service:'Service type',table:'Table service',room:'Room service',roomNo:'Room number',note:'Order note',allergy:'Allergy / dietary note',confirm1:'1st confirmation: Is your cart correct?',confirm2:'2nd confirmation: Send this order to the restaurant?',send:'Send Order',pending:'Your order has been sent to the restaurant and is waiting for staff approval.',staff:'Staff will accept it from the admin panel.',pricePending:'Price on staff approval',total:'Total',tryAgain:'Try again'},
  de:{title:'Kassandra Restaurant Bestellung',lead:'Tischbestellung per QR',language:'Sprache wählen',meal:'Für welche Mahlzeit möchten Sie bestellen?',breakfast:'Frühstück',lunch:'Mittagessen',dinner:'Abendessen',continue:'Weiter',back:'Zurück',menu:'Menü',pdf:'PDF-Menü öffnen',add:'Hinzufügen',cart:'Warenkorb',empty:'Ihr Warenkorb ist leer.',service:'Serviceart',table:'Tischservice',room:'Zimmerservice',roomNo:'Zimmernummer',note:'Bestellnotiz',allergy:'Allergie / besondere Präferenz',confirm1:'1. Bestätigung: Ist Ihr Warenkorb korrekt?',confirm2:'2. Bestätigung: Bestellung an das Restaurant senden?',send:'Bestellung senden',pending:'Ihre Bestellung wurde an das Restaurant übermittelt und wartet auf Bestätigung durch das Personal.',staff:'Das Personal nimmt die Bestellung im Admin-Panel an.',pricePending:'Preis nach Personalbestätigung',total:'Gesamt',tryAgain:'Erneut versuchen'},
  ru:{title:'Заказ в ресторане Kassandra',lead:'Заказ к столу по QR-коду',language:'Выберите язык',meal:'Для какого приема пищи вы хотите сделать заказ?',breakfast:'Завтрак',lunch:'Обед',dinner:'Ужин',continue:'Продолжить',back:'Назад',menu:'Меню',pdf:'Открыть PDF-меню',add:'Добавить',cart:'Корзина',empty:'Ваша корзина пуста.',service:'Тип обслуживания',table:'Обслуживание за столом',room:'Доставка в номер',roomNo:'Номер комнаты',note:'Комментарий к заказу',allergy:'Аллергия / особые предпочтения',confirm1:'1-е подтверждение: корзина верна?',confirm2:'2-е подтверждение: отправить заказ в ресторан?',send:'Отправить заказ',pending:'Ваш заказ отправлен в ресторан и ожидает подтверждения персоналом.',staff:'Персонал примет заказ в админ-панели.',pricePending:'Цена после подтверждения персоналом',total:'Итого',tryAgain:'Попробовать снова'},
  ar:{title:'طلب مطعم Kassandra',lead:'طلب الطاولة عبر رمز QR',language:'اختر اللغة',meal:'لأي وجبة تريد الطلب؟',breakfast:'الإفطار',lunch:'الغداء',dinner:'العشاء',continue:'متابعة',back:'رجوع',menu:'القائمة',pdf:'فتح قائمة PDF',add:'إضافة',cart:'السلة',empty:'سلتك فارغة.',service:'نوع الخدمة',table:'خدمة الطاولة',room:'خدمة الغرفة',roomNo:'رقم الغرفة',note:'ملاحظة الطلب',allergy:'حساسية / تفضيل خاص',confirm1:'التأكيد الأول: هل السلة صحيحة؟',confirm2:'التأكيد الثاني: هل تريد إرسال الطلب إلى المطعم؟',send:'إرسال الطلب',pending:'تم إرسال طلبك إلى المطعم وهو بانتظار موافقة الموظف.',staff:'سيقبل الموظف الطلب من لوحة الإدارة.',pricePending:'السعر بعد تأكيد الموظف',total:'الإجمالي',tryAgain:'حاول مرة أخرى'},
  fr:{title:'Commande Kassandra Restaurant',lead:'Commande à table par QR',language:'Choisir la langue',meal:'Pour quel repas souhaitez-vous commander ?',breakfast:'Petit-déjeuner',lunch:'Déjeuner',dinner:'Dîner',continue:'Continuer',back:'Retour',menu:'Menu',pdf:'Ouvrir le menu PDF',add:'Ajouter',cart:'Panier',empty:'Votre panier est vide.',service:'Type de service',table:'Service à table',room:'Service en chambre',roomNo:'Numéro de chambre',note:'Note de commande',allergy:'Allergie / préférence spéciale',confirm1:'1re confirmation : votre panier est-il correct ?',confirm2:'2e confirmation : envoyer cette commande au restaurant ?',send:'Envoyer la commande',pending:'Votre commande a été envoyée au restaurant et attend l’approbation du personnel.',staff:'Le personnel acceptera la commande depuis le panneau admin.',pricePending:'Prix après confirmation du personnel',total:'Total',tryAgain:'Réessayer'},
  nl:{title:'Kassandra Restaurant Bestelling',lead:'Tafelbestelling via QR',language:'Kies taal',meal:'Voor welke maaltijd wilt u bestellen?',breakfast:'Ontbijt',lunch:'Lunch',dinner:'Diner',continue:'Doorgaan',back:'Terug',menu:'Menu',pdf:'PDF-menu openen',add:'Toevoegen',cart:'Winkelmand',empty:'Uw winkelmand is leeg.',service:'Servicetype',table:'Tafelservice',room:'Roomservice',roomNo:'Kamernummer',note:'Bestelnotitie',allergy:'Allergie / speciale voorkeur',confirm1:'1e bevestiging: klopt uw winkelmand?',confirm2:'2e bevestiging: bestelling naar het restaurant sturen?',send:'Bestelling verzenden',pending:'Uw bestelling is naar het restaurant verzonden en wacht op goedkeuring van het personeel.',staff:'Het personeel accepteert de bestelling via het adminpaneel.',pricePending:'Prijs na bevestiging door personeel',total:'Totaal',tryAgain:'Opnieuw proberen'},
  es:{title:'Pedido Kassandra Restaurant',lead:'Pedido de mesa por QR',language:'Elegir idioma',meal:'¿Para qué comida desea pedir?',breakfast:'Desayuno',lunch:'Almuerzo',dinner:'Cena',continue:'Continuar',back:'Atrás',menu:'Menú',pdf:'Abrir menú PDF',add:'Añadir',cart:'Carrito',empty:'Su carrito está vacío.',service:'Tipo de servicio',table:'Servicio de mesa',room:'Servicio a la habitación',roomNo:'Número de habitación',note:'Nota del pedido',allergy:'Alergia / preferencia especial',confirm1:'1.ª confirmación: ¿su carrito es correcto?',confirm2:'2.ª confirmación: ¿enviar este pedido al restaurante?',send:'Enviar pedido',pending:'Su pedido fue enviado al restaurante y espera aprobación del personal.',staff:'El personal aceptará el pedido desde el panel de administración.',pricePending:'Precio tras confirmación del personal',total:'Total',tryAgain:'Intentar de nuevo'}
};
function t(key){return (i18n[state.lang]||i18n.en)[key]||i18n.en[key]||key}
function esc(value){return String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;')}
function money(value){if(value===null||value===undefined||value==='')return t('pricePending');const n=Number(value);return Number.isFinite(n)?new Intl.NumberFormat(state.lang==='tr'?'tr-TR':'en-US',{maximumFractionDigits:2}).format(n)+' ₺':esc(value)}
function allItems(){if(!state.cfg)return[];if(state.meal==='breakfast')return state.cfg.breakfast_items||[];return state.cfg.catalog_items||[]}
function itemName(item){if(state.lang==='tr')return item.name_tr||item.name_en||item.menu_item_id;return item.name_en||item.name_tr||item.menu_item_id}
function cartRows(){const byId=Object.fromEntries(allItems().map(item=>[item.menu_item_id,item]));return Object.entries(state.cart).map(([id,row])=>({...row,item:byId[id]})).filter(row=>row.item)}
function totalText(){let total=0;let hasMissing=false;for(const row of cartRows()){if(row.item.price_try===null||row.item.price_try===undefined){hasMissing=true;continue}total+=Number(row.item.price_try)*row.quantity}return hasMissing?money(null):money(total)}
function header(){const place=state.cfg?`Masa ${esc(state.cfg.table_no)} · ${esc(state.cfg.venue)}`:'-';return `<div class="order-top"><div class="brand"><h1>${esc(t('title'))}</h1><p>${esc(t('lead'))}</p></div><span class="pill">${place}</span></div>`}
function stepper(active){return `<div class="stepper">${[1,2,3,4,5].map(n=>`<span class="dot ${n<=active?'active':''}"></span>`).join('')}</div>`}
function render(){if(state.step==='loading')return app.innerHTML='<div class="panel">Yükleniyor...</div>';if(state.error)return app.innerHTML=`${header()}<div class="panel notice error">${esc(state.error)}<div class="footer-actions"><button class="secondary" data-action="reload">${esc(t('tryAgain'))}</button></div></div>`;if(state.step==='language')return renderLanguage();if(state.step==='meal')return renderMeal();if(state.step==='menu')return renderMenu();if(state.step==='service')return renderService();if(state.step==='confirm1')return renderConfirm(1);if(state.step==='confirm2')return renderConfirm(2);if(state.step==='success')return renderSuccess();}
function renderLanguage(){app.innerHTML=`${header()}<section class="panel">${stepper(1)}<h2>${esc(t('language'))}</h2><div class="grid">${(state.cfg.supported_languages||[]).map(lang=>`<button class="card ${lang.code===state.lang?'active':''}" data-lang="${esc(lang.code)}"><strong>${esc(lang.label)}</strong><small>${esc(lang.code)}</small></button>`).join('')}</div><div class="footer-actions"><button class="primary" data-step="meal">${esc(t('continue'))}</button></div></section>`}
function renderMeal(){app.innerHTML=`${header()}<section class="panel">${stepper(2)}<h2>${esc(t('meal'))}</h2><div class="grid">${['breakfast','lunch','dinner'].map(meal=>`<button class="card ${meal===state.meal?'active':''}" data-meal="${meal}"><strong>${esc(t(meal))}</strong></button>`).join('')}</div><div class="footer-actions"><button class="secondary" data-step="language">${esc(t('back'))}</button><button class="primary" data-step="menu" ${state.meal?'':'disabled'}>${esc(t('continue'))}</button></div></section>`}
function renderMenu(){const items=allItems();const mealCfg=state.cfg.meal_periods?.[state.meal]||{};const pdfs=(mealCfg.pdf_keys||[]).map(key=>state.cfg.pdf_menus?.[key]).filter(Boolean);app.innerHTML=`${header()}<section class="panel">${stepper(3)}<h2>${esc(t('menu'))}</h2><div class="toolbar">${pdfs.map(pdf=>`<a class="secondary" href="${esc(pdf.url)}" target="_blank" rel="noopener">${esc(pdf.label)} · ${esc(t('pdf'))}</a>`).join('')}</div><div class="items">${items.map(item=>`<article class="card"><div class="item-title"><b>${esc(itemName(item))}</b><span class="price">${money(item.price_try)}</span></div><small>${esc(item.description_tr||item.description_en||'')}</small><div class="footer-actions"><button class="primary" data-add="${esc(item.menu_item_id)}">${esc(t('add'))}</button></div></article>`).join('')}</div>${renderCart()}<div class="footer-actions"><button class="secondary" data-step="meal">${esc(t('back'))}</button><button class="primary" data-step="service" ${cartRows().length?'':'disabled'}>${esc(t('continue'))}</button></div></section>`}
function renderCart(){const rows=cartRows();if(!rows.length)return `<div class="empty">${esc(t('empty'))}</div>`;return `<h3>${esc(t('cart'))}</h3><div class="summary">${rows.map(row=>`<div class="summary-row"><span>${row.quantity}x ${esc(itemName(row.item))}</span><span><button class="secondary" data-dec="${esc(row.item.menu_item_id)}">-</button> <button class="secondary" data-inc="${esc(row.item.menu_item_id)}">+</button></span></div>`).join('')}<div class="summary-row"><strong>${esc(t('total'))}</strong><strong>${totalText()}</strong></div></div>`}
function renderService(){app.innerHTML=`${header()}<section class="panel">${stepper(4)}<h2>${esc(t('service'))}</h2><div class="grid-2"><button class="card ${state.serviceType==='table_service'?'active':''}" data-service="table_service"><strong>${esc(t('table'))}</strong><small>Masa ${esc(state.cfg.table_no)}</small></button><button class="card ${state.serviceType==='room_service'?'active':''}" data-service="room_service"><strong>${esc(t('room'))}</strong></button></div><form id="serviceForm"><div class="field" ${state.serviceType==='room_service'?'':'hidden'}><label>${esc(t('roomNo'))}</label><input name="roomNumber" value="${esc(state.roomNumber)}" maxlength="32"></div><div class="field"><label>${esc(t('note'))}</label><textarea name="customerNote" maxlength="500">${esc(state.customerNote)}</textarea></div><div class="field"><label>${esc(t('allergy'))}</label><textarea name="allergyNote" maxlength="500">${esc(state.allergyNote)}</textarea></div><div class="footer-actions"><button class="secondary" type="button" data-step="menu">${esc(t('back'))}</button><button class="primary" type="submit">${esc(t('continue'))}</button></div></form></section>`}
function renderConfirm(number){app.innerHTML=`${header()}<section class="panel">${stepper(5)}<h2>${esc(number===1?t('confirm1'):t('confirm2'))}</h2>${renderCart()}<div class="notice">${esc(t('staff'))}</div><div class="footer-actions"><button class="secondary" data-step="${number===1?'service':'confirm1'}">${esc(t('back'))}</button><button class="primary" data-action="${number===1?'confirm-once':'submit'}" ${state.submitting?'disabled':''}>${esc(number===1?t('continue'):t('send'))}</button></div></section>`}
function renderSuccess(){app.innerHTML=`${header()}<section class="panel"><h2>${esc(t('pending'))}</h2><p class="notice">${esc(t('staff'))}</p><p class="pill">${esc(state.success?.order_id||'')}</p></section>`}
app.addEventListener('click',event=>{const node=event.target.closest('button,a');if(!node)return;if(node.dataset.lang){state.lang=node.dataset.lang;render();return}if(node.dataset.meal){state.meal=node.dataset.meal;state.cart={};render();return}if(node.dataset.service){state.serviceType=node.dataset.service;render();return}if(node.dataset.step){state.step=node.dataset.step;render();return}if(node.dataset.add){state.cart[node.dataset.add]={quantity:(state.cart[node.dataset.add]?.quantity||0)+1};render();return}if(node.dataset.inc){state.cart[node.dataset.inc].quantity+=1;render();return}if(node.dataset.dec){const row=state.cart[node.dataset.dec];if(row){row.quantity-=1;if(row.quantity<=0)delete state.cart[node.dataset.dec]}render();return}if(node.dataset.action==='confirm-once'){state.step='confirm2';render();return}if(node.dataset.action==='submit'){submitOrder();return}if(node.dataset.action==='reload'){window.location.reload();}});
app.addEventListener('submit',event=>{event.preventDefault();const form=new FormData(event.target);state.roomNumber=String(form.get('roomNumber')||'').trim();state.customerNote=String(form.get('customerNote')||'').trim();state.allergyNote=String(form.get('allergyNote')||'').trim();if(state.serviceType==='room_service'&&!state.roomNumber){event.target.roomNumber.focus();return}state.step='confirm1';render();});
async function submitOrder(){state.submitting=true;render();const items=cartRows().map(row=>({menu_item_id:row.item.menu_item_id,quantity:row.quantity}));try{const response=await fetch('/api/v1/public/restaurant-order/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,language_code:state.lang,meal_period:state.meal,service_type:state.serviceType,items,customer_note:state.customerNote||null,allergy_note:state.allergyNote||null,room_number:state.serviceType==='room_service'?state.roomNumber:null,customer_confirmation_count:2})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.detail||'Islem tamamlanamadi.');state.success=payload;state.step='success'}catch(error){state.error=error.message||'Islem tamamlanamadi.'}finally{state.submitting=false;render();}}
async function init(){if(!token){state.error='Sipariş bağlantısı eksik.';return render()}try{const response=await fetch('/api/v1/public/restaurant-order/config?token='+encodeURIComponent(token));const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.detail||'Sipariş ekranı açılamadı.');state.cfg=payload;state.lang=payload.default_language||'tr';state.step='language'}catch(error){state.error=error.message||'Sipariş ekranı açılamadı.'}render();}
init();
"""
