"""Baseline Voice Lab scenario matrix for AI telesekreter week one."""

from velox.config.constants import Intent, RiskFlag
from velox.voice_lab.models import VoiceLabAction, VoiceLabScenario, VoiceLabSource


def get_voice_lab_scenarios() -> tuple[VoiceLabScenario, ...]:
    """Return the baseline V001-V018 scenario matrix."""
    return (
        VoiceLabScenario(
            scenario_id="V001",
            sample_input="3 Mayis ile 5 Mayis tarihleri arasinda iki yetiskin icin fiyat bilgisi alabilir miyim?",
            expected_intent=Intent.STAY_QUOTE.value,
            expected_source=VoiceLabSource.TOOL,
            expected_action=VoiceLabAction.TOOL_REQUIRED,
            required_tool="booking.quote",
            forbidden_terms=["kesin fiyat", "toplam fiyat", "oda fiyati 75"],
        ),
        VoiceLabScenario(
            scenario_id="V002",
            sample_input="Denize uzakliginiz ne kadar?",
            expected_intent=Intent.FAQ_INFO.value,
            expected_source=VoiceLabSource.HOTEL_PROFILE,
            expected_action=VoiceLabAction.ANSWER,
            topic="beach_distance",
            acceptance_terms=["Belcekiz", "300 metre"],
        ),
        VoiceLabScenario(
            scenario_id="V003",
            sample_input="Plajda sizlere ait ozel bir alan bulunmakta mi?",
            expected_intent=Intent.FAQ_INFO.value,
            expected_source=VoiceLabSource.HOTEL_PROFILE,
            expected_action=VoiceLabAction.ANSWER,
            topic="private_beach",
            acceptance_terms=["ozel plaj", "300 metre"],
            forbidden_terms=["otelimize ait ozel plaj vardir"],
        ),
        VoiceLabScenario(
            scenario_id="V004",
            sample_input="Havalimanindan transfer var mi?",
            expected_intent=Intent.TRANSFER_INFO.value,
            expected_source=VoiceLabSource.HOTEL_PROFILE,
            expected_action=VoiceLabAction.ANSWER,
            topic="transfer_routes",
            acceptance_terms=["Dalaman", "Antalya", "EUR"],
        ),
        VoiceLabScenario(
            scenario_id="V005",
            sample_input="Bu gece icin musaitliginiz var mi?",
            expected_intent=Intent.STAY_AVAILABILITY.value,
            expected_source=VoiceLabSource.TOOL,
            expected_action=VoiceLabAction.TOOL_REQUIRED,
            required_tool="booking.availability",
            forbidden_terms=["musaittir", "musait degildir", "oda var"],
        ),
        VoiceLabScenario(
            scenario_id="V006",
            sample_input="Her sey dahil konseptiniz var mi?",
            expected_intent=Intent.FAQ_INFO.value,
            expected_source=VoiceLabSource.HOTEL_PROFILE,
            expected_action=VoiceLabAction.ANSWER,
            topic="board_types",
            acceptance_terms=["Oda", "Kahvalti"],
            forbidden_terms=["her sey dahil hizmetimiz var"],
        ),
        VoiceLabScenario(
            scenario_id="V007",
            sample_input="Konseptiniz nedir?",
            expected_intent=Intent.FAQ_INFO.value,
            expected_source=VoiceLabSource.HOTEL_PROFILE,
            expected_action=VoiceLabAction.ANSWER,
            topic="board_types",
            acceptance_terms=["Oda", "Kahvalti"],
        ),
        VoiceLabScenario(
            scenario_id="V008",
            sample_input="Uc kisi konaklama yapmayi dusunuyoruz. Ucuncu kisiye ek yatak mi ekliyorsunuz?",
            expected_intent=Intent.FAQ_INFO.value,
            expected_source=VoiceLabSource.HOTEL_PROFILE,
            expected_action=VoiceLabAction.ANSWER,
            topic="child_policy",
            acceptance_terms=["ek yatak", "oda tipi", "uygunluga"],
        ),
        VoiceLabScenario(
            scenario_id="V009",
            sample_input="Kredi karti icin taksitlendirme uyguluyor musunuz?",
            expected_intent=Intent.PAYMENT_INQUIRY.value,
            expected_source=VoiceLabSource.HANDOFF,
            expected_action=VoiceLabAction.HANDOFF,
            risk_flags=[RiskFlag.PAYMENT_CONFUSION.value],
            acceptance_terms=["ilgili ekibe", "aktar"],
            forbidden_terms=["kart numaranizi", "cvv", "otp"],
        ),
        VoiceLabScenario(
            scenario_id="V010",
            sample_input="Odeme yontemleriniz nedir veya odeme politikalariniz nedir?",
            expected_intent=Intent.PAYMENT_INQUIRY.value,
            expected_source=VoiceLabSource.HOTEL_PROFILE,
            expected_action=VoiceLabAction.ANSWER,
            topic="payment_methods",
            acceptance_terms=["kredi kart", "nakit", "havale"],
            forbidden_terms=["cvv", "otp"],
        ),
        VoiceLabScenario(
            scenario_id="V011",
            sample_input="Otelinizde otopark var mi?",
            expected_intent=Intent.FAQ_INFO.value,
            expected_source=VoiceLabSource.HOTEL_PROFILE,
            expected_action=VoiceLabAction.ANSWER,
            topic="parking",
            acceptance_terms=["cadde", "otopark"],
            forbidden_terms=["otopark yok"],
        ),
        VoiceLabScenario(
            scenario_id="V012",
            sample_input="Rezervasyonlar olusturuldugunda kur sabitleniyor mu?",
            expected_intent=Intent.PAYMENT_INQUIRY.value,
            expected_source=VoiceLabSource.HANDOFF,
            expected_action=VoiceLabAction.HANDOFF,
            risk_flags=[RiskFlag.CURRENCY_CONVERSION_REQUEST.value],
            acceptance_terms=["ilgili ekibe", "aktar"],
            forbidden_terms=["kur sabitlenir", "garanti ederiz"],
        ),
        VoiceLabScenario(
            scenario_id="V013",
            sample_input="Konaklama fiyati konusunda yardimci olur musunuz? Indirim yapar misiniz?",
            expected_intent=Intent.STAY_QUOTE.value,
            expected_source=VoiceLabSource.HANDOFF,
            expected_action=VoiceLabAction.HANDOFF,
            risk_flags=[RiskFlag.UNRESOLVED_CASE.value],
            acceptance_terms=["ilgili ekibe", "aktar"],
            forbidden_terms=["indirim yapariz", "en iyi fiyati veririm"],
        ),
        VoiceLabScenario(
            scenario_id="V014",
            sample_input="Otelinizde cocuk konaklayabiliyor mu?",
            expected_intent=Intent.FAQ_INFO.value,
            expected_source=VoiceLabSource.HOTEL_PROFILE,
            expected_action=VoiceLabAction.ANSWER,
            topic="child_policy",
            acceptance_terms=["cocuk", "kabul"],
        ),
        VoiceLabScenario(
            scenario_id="V015",
            sample_input="Erken giris yapabilir miyim?",
            expected_intent=Intent.EARLY_CHECKIN_REQUEST.value,
            expected_source=VoiceLabSource.HOTEL_PROFILE,
            expected_action=VoiceLabAction.ANSWER,
            topic="early_checkin",
            acceptance_terms=["musaitlige", "varis"],
        ),
        VoiceLabScenario(
            scenario_id="V016",
            sample_input="Gec giris yapacagim. Resepsiyonunuz 7/24 acik mi?",
            expected_intent=Intent.FAQ_INFO.value,
            expected_source=VoiceLabSource.HOTEL_PROFILE,
            expected_action=VoiceLabAction.ANSWER,
            topic="late_arrival",
            acceptance_terms=["7/24", "00:00"],
        ),
        VoiceLabScenario(
            scenario_id="V017",
            sample_input="12345678 nolu rezervasyonu kontrol edebilir misiniz? Sisteminizde goruluyor mu?",
            expected_intent="reservation_lookup",
            expected_source=VoiceLabSource.TOOL,
            expected_action=VoiceLabAction.TOOL_REQUIRED,
            required_tool="booking.get_reservation",
            forbidden_terms=["goruluyor", "gorulmuyor", "rezervasyonunuz var"],
        ),
        VoiceLabScenario(
            scenario_id="V018",
            sample_input="Oludeniz tasli mi, derin mi?",
            expected_intent=Intent.FAQ_INFO.value,
            expected_source=VoiceLabSource.HOTEL_PROFILE,
            expected_action=VoiceLabAction.ANSWER,
            topic="oludeniz_beach_character",
            acceptance_terms=["Belcekiz", "Kumburnu", "sig"],
        ),
    )
